### ISSUE TITLE
CSS Tweaks for overriding jQuery UI CSS by Helen Hou-Sandi

### ISSUE THREAD

**Issue by shazahm1** [stuttter/wp-datepicker-styling#2]
I use the [jQuery UI styles by Helen Hou-Sandi](https://github.com/helenhousandi/wp-admin-jquery-ui) in my plugins its been very useful even though the styling is a bit dated. My need is to use both because her CSS provides support for all of jQuery UI elements. For the most part this works great by enqueueing her CSS as a dependency of your CSS file. Most of it overrides pretty well but it needed a few tweaks in order to completely override the styles in her CSS. Would you be interested in a pull request that included those tweaks.

**Comment by johnjamesjacoby** [comment]
Yes, please.

**Comment by shazahm1** [comment]
Alrighty... just sent a pull. Much of the diff comes from swapping spaces for tabs for the indentation. It was a little inconsistent in the original file going back for forth between the two. When I copy/pasted that changes, my IDE "fixed" it.

**Comment by johnjamesjacoby** [comment]
Thanks for this. Sorry to make you do the whitespace cleanup!

**Comment by johnjamesjacoby** [comment]
Merged in 7a4fa8399bde3b97f2a8115e87d2f524e27f88a7.

Thanks again!
