### ISSUE TITLE
Does this work on frontend?

### ISSUE THREAD

**Issue by ashokrane** [stuttter/wp-datepicker-styling#4]
Does this work on the frontend with different jQuery themes or it works only in the admin dashboard?

**Comment by johnjamesjacoby** [comment]
Good question. This is primarily targeting the styling within `wp-admin`.

It would not be too difficult to adapt it for other front-end frameworks (Bootstrap, Semantic UI, etc...) though most WordPress themes don't really use these for theme-side form elements yet.

@ashokrane do you have any specific themes or use-cases in mind?

**Comment by ashokrane** [comment]
@johnjamesjacoby We actually took this & applied it on our frontend jQuery calendars. 3 of our core plugins use the jQuery calendar & customers have been asking for calendars like Pickadate & others instead of jQuery. When I came across this new flat styling, I liked it & we have since implemented it in our plugin's calendars.
Thanks to you for making this. :)

**Comment by johnjamesjacoby** [comment]
You're welcome. Thanks for taking the time to comment here. I really appreciate it. 👍
